// <auto-generated />
namespace Shahrdari.DataAccessLayer
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Shahrdari : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Shahrdari));
        
        string IMigrationMetadata.Id
        {
            get { return "201903280820372_Shahrdari"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
